# Generated by Django 5.0 on 2024-01-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification_screenshot_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[(1, 'active'), (2, 'completed'), (3, 'cancelled'), (4, 'expired')], default='active', max_length=20),
        ),
    ]
