# Generated by Django 5.0.1 on 2024-01-07 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='taken_on'),
            preserve_default=False,
        ),
    ]
