# Generated by Django 5.0.1 on 2024-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_task_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_hours',
            field=models.BigIntegerField(default=0),
        ),
    ]
