# Generated by Django 5.0.1 on 2024-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_work_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='work_hours',
            new_name='work_minutes',
        ),
    ]
