# Generated by Django 5.0.1 on 2024-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_work_hours_user_work_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
